# Generated by Django 2.2.2 on 2019-06-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_usergroup_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='title',
            field=models.IntegerField(choices=[(1, '前端小组'), (2, 'android小组'), (3, 'java小组')]),
        ),
    ]
